In [1]:
!pip install numpy pandas matplotlib seaborn scikit-learn opencv-python librosa


In [1]:
import zipfile

zip_path = "/content/parkinsons.zip"
extract_folder = "/content/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

import os
print(os.listdir('/content/'))


['.config', 'telemonitoring', 'parkinsons.data', 'handwriting.zip', 'parkinsons.names', 'parkinsons.zip', 'sample_data']


In [2]:
import pandas as pd

# Load with correct delimiter (since the file may not have headers)
df_voice = pd.read_csv('/content/parkinsons.data')

# Check the first few rows
print(df_voice.head())


             name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.0654

In [3]:
print(df_voice.columns)


Index(['name', 'MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')


In [4]:
from sklearn.model_selection import train_test_split

X_voice = df_voice.drop(['name', 'status'], axis=1)
y_voice = df_voice['status']

X_train_voice, X_test_voice, y_train_voice, y_test_voice = train_test_split(X_voice, y_voice, test_size=0.2, random_state=42)


In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clf_voice = RandomForestClassifier()
clf_voice.fit(X_train_voice, y_train_voice)

y_pred_voice = clf_voice.predict(X_test_voice)
print("Voice Data Accuracy:", accuracy_score(y_test_voice, y_pred_voice))


Voice Data Accuracy: 0.9487179487179487


In [6]:
!pip install numpy pandas matplotlib seaborn scikit-learn opencv-python librosa


In [7]:
import zipfile

zip_path = "/content/parkinsons.zip"  # Path to the zip file
extract_folder = "/content/"  # Folder to extract files

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

import os
print(os.listdir('/content/'))  # Check extracted files


['.config', 'telemonitoring', 'parkinsons.data', 'handwriting.zip', 'parkinsons.names', 'parkinsons.zip', 'sample_data']


In [8]:
import pandas as pd

# Load the voice data
df_voice = pd.read_csv('/content/parkinsons.data')

# Load the UPDRS (clinical) data
df_updrs = pd.read_csv('/content/telemonitoring/parkinsons_updrs.data')

# Display first few rows to inspect the data
print(df_voice.head())
print(df_updrs.head())


             name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.0654

In [9]:
X_voice = df_voice.drop(['name', 'status'], axis=1)  # Drop 'name' (patient ID) and 'status' columns
y_voice = df_voice['status']  # 'status' is the target label (0 = Healthy, 1 = Parkinson's)


In [10]:
print(df_updrs.columns)


Index(['subject#', 'age', 'sex', 'test_time', 'motor_UPDRS', 'total_UPDRS',
       'Jitter(%)', 'Jitter(Abs)', 'Jitter:RAP', 'Jitter:PPQ5', 'Jitter:DDP',
       'Shimmer', 'Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'Shimmer:APQ11', 'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE'],
      dtype='object')


In [11]:
# Assuming motor_UPDRS > 30 indicates Parkinson's disease
df_updrs['status'] = (df_updrs['motor_UPDRS'] > 30).astype(int)

# Features (dropping 'subject#' and 'status' columns, as 'status' is now the label)
X_updrs = df_updrs.drop(['subject#', 'status'], axis=1)

# Target variable (status)
y_updrs = df_updrs['status']


In [12]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train_updrs, X_test_updrs, y_train_updrs, y_test_updrs = train_test_split(X_updrs, y_updrs, test_size=0.2, random_state=42)


In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Initialize and train the classifier
clf_updrs = RandomForestClassifier()
clf_updrs.fit(X_train_updrs, y_train_updrs)

# Predict on the test set
y_pred_updrs = clf_updrs.predict(X_test_updrs)

# Evaluate the model
print("UPDRS Data Accuracy:", accuracy_score(y_test_updrs, y_pred_updrs))


UPDRS Data Accuracy: 1.0


In [19]:
import zipfile

zip_path = "/content/handwriting.zip"
extract_folder = "/content/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

In [20]:
import os
print(os.listdir('/content/handwriting/spiral/training'))

['healthy', 'parkinson']


In [21]:
import cv2
import os
import numpy as np

# Function to load images from a folder and assign label (1 for Parkinson's, 0 for Healthy)
def load_images_from_folder(folder, label):
    images = []
    labels = []
    for filename in os.listdir(folder):
        img_path = os.path.join(folder, filename)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is not None:
            img = cv2.resize(img, (100, 100))  # Resize to 100x100
            images.append(img.flatten())      # Flatten the image to 1D
            labels.append(label)
    return images, labels

In [22]:
parkinsons_spiral, labels_spiral = load_images_from_folder('/content/handwriting/spiral/training/parkinson', 1)
healthy_spiral, labels_healthy_spiral = load_images_from_folder('/content/handwriting/spiral/training/healthy', 0)

# Combine spiral data
X_spiral = parkinsons_spiral + healthy_spiral
y_spiral = labels_spiral + labels_healthy_spiral

In [23]:
parkinsons_wave, labels_wave = load_images_from_folder('/content/handwriting/wave/training/parkinson', 1)
healthy_wave, labels_healthy_wave = load_images_from_folder('/content/handwriting/wave/training/healthy', 0)

# Combine wave data
X_wave = parkinsons_wave + healthy_wave
y_wave = labels_wave + labels_healthy_wave

In [24]:
X_spiral = np.array(X_spiral)
y_spiral = np.array(y_spiral)

X_wave = np.array(X_wave)
y_wave = np.array(y_wave)

print(f'Spiral Images Shape: {X_spiral.shape}, Spiral Labels Shape: {y_spiral.shape}')
print(f'Wave Images Shape: {X_wave.shape}, Wave Labels Shape: {y_wave.shape}')


Spiral Images Shape: (72, 10000), Spiral Labels Shape: (72,)
Wave Images Shape: (72, 10000), Wave Labels Shape: (72,)


In [25]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Split data (80% train, 20% test)
X_train_spiral, X_test_spiral, y_train_spiral, y_test_spiral = train_test_split(X_spiral, y_spiral, test_size=0.2, random_state=42)

# Train a simple SVM model
model_spiral = SVC(kernel='linear')
model_spiral.fit(X_train_spiral, y_train_spiral)

# Predict
y_pred_spiral = model_spiral.predict(X_test_spiral)

# Evaluate
print("\nSpiral Drawings Model Evaluation:")
print("Accuracy:", accuracy_score(y_test_spiral, y_pred_spiral))
print("Classification Report:\n", classification_report(y_test_spiral, y_pred_spiral))
print("Confusion Matrix:\n", confusion_matrix(y_test_spiral, y_pred_spiral))



Spiral Drawings Model Evaluation:
Accuracy: 0.7333333333333333
Classification Report:
               precision    recall  f1-score   support

           0       0.56      1.00      0.71         5
           1       1.00      0.60      0.75        10

    accuracy                           0.73        15
   macro avg       0.78      0.80      0.73        15
weighted avg       0.85      0.73      0.74        15

Confusion Matrix:
 [[5 0]
 [4 6]]


In [26]:
# Split data (80% train, 20% test)
X_train_wave, X_test_wave, y_train_wave, y_test_wave = train_test_split(X_wave, y_wave, test_size=0.2, random_state=42)

# Train a simple SVM model
model_wave = SVC(kernel='linear')
model_wave.fit(X_train_wave, y_train_wave)

# Predict
y_pred_wave = model_wave.predict(X_test_wave)

# Evaluate
print("\nWave Drawings Model Evaluation:")
print("Accuracy:", accuracy_score(y_test_wave, y_pred_wave))
print("Classification Report:\n", classification_report(y_test_wave, y_pred_wave))
print("Confusion Matrix:\n", confusion_matrix(y_test_wave, y_pred_wave))



Wave Drawings Model Evaluation:
Accuracy: 0.5333333333333333
Classification Report:
               precision    recall  f1-score   support

           0       0.38      0.60      0.46         5
           1       0.71      0.50      0.59        10

    accuracy                           0.53        15
   macro avg       0.54      0.55      0.52        15
weighted avg       0.60      0.53      0.55        15

Confusion Matrix:
 [[3 2]
 [5 5]]


In [27]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Combine the spiral and wave data (X) and labels (y)
X_combined = np.concatenate((X_spiral, X_wave), axis=0)  # Combine features (images)
y_combined = np.concatenate((y_spiral, y_wave), axis=0)  # Combine labels

# Split the combined data into training and testing sets (80% train, 20% test)
X_train_combined, X_test_combined, y_train_combined, y_test_combined = train_test_split(X_combined, y_combined, test_size=0.2, random_state=42)

# Train a simple SVM model on the combined data
model_combined = SVC(kernel='linear')
model_combined.fit(X_train_combined, y_train_combined)

# Predict with the combined model
y_pred_combined = model_combined.predict(X_test_combined)

# Evaluate the model performance
print("\nCombined Handwriting Model Evaluation:")
print("Accuracy:", accuracy_score(y_test_combined, y_pred_combined))
print("Classification Report:\n", classification_report(y_test_combined, y_pred_combined))
print("Confusion Matrix:\n", confusion_matrix(y_test_combined, y_pred_combined))




Combined Handwriting Model Evaluation:
Accuracy: 0.5517241379310345
Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.60      0.58        15
           1       0.54      0.50      0.52        14

    accuracy                           0.55        29
   macro avg       0.55      0.55      0.55        29
weighted avg       0.55      0.55      0.55        29

Confusion Matrix:
 [[9 6]
 [7 7]]


In [28]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# Assuming you've already prepared your training data (X_train_combined, y_train_combined)
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}

# Create a basic SVM model
svm = SVC()

# Set up GridSearchCV to find the best model
grid_search = GridSearchCV(svm, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_combined, y_train_combined)

# The best model after grid search
best_model = grid_search.best_estimator_

# Save the best model
import joblib
joblib.dump(best_model, 'parkinsons_model.pkl')


['parkinsons_model.pkl']

In [29]:
from sklearn.svm import SVC

# Train a model (e.g., SVM)
model = SVC(kernel='rbf', C=1, gamma='scale')
model.fit(X_train_combined, y_train_combined)

# Assign the trained model to best_model
best_model = model

# Save the model
import joblib
joblib.dump(best_model, 'parkinsons_model.pkl')


['parkinsons_model.pkl']

In [30]:
import joblib

# Load the saved model
best_model = joblib.load('parkinsons_model.pkl')


In [31]:
pip install flask


In [33]:
from google.colab import files
files.download('parkinsons_model.pkl')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>